url: "https://tabokie.github.io"
title: "Xinye Tao"
lang: "en-US"

author:
  name: "Xinye Tao"
  email: "xy.tao@outlook.com"

social:
  name: "Xinye Tao"
  links:
    - "https://github.com/tabokie"
    - "https://www.douban.com/people/91872582"

webmaster_verifications:
  google: "LwllE8LNzqSKfduvBO0DPUFHyeOhhYuk7QeKjmQHwKE"

collections:
  topics:
    output: true
  subtopics:
    output: true
  lists:
    output: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
